name: "phpunit"

on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest

        name: phpunit

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: none

            -   name: Install dependencies
                run: composer install --prefer-stable --prefer-dist --no-progress --no-interaction --no-cache

            -   name: Execute tests
                run: sudo vendor/bin/phpunit
